---
tinyproxy_listen: 172.31.2.131
tinyproxy_bind_same: True
tinyproxy_allow: ['172.31.1.0/24']
tinyproxy_disable_via: True
tinyproxy_loglevel: Critical

pkg_config_openbsd_mtier_enable: True

my_grp_packages: [ 'tinyproxy--']
samba_interfaces: 'em1'
samba_additional_settings:
  - "map to guest = bad user"
  - "guest account = nobody"
  - "bind interfaces only = yes"
samba_shares:
  - name: tftp
    path: /tftpboot
    public: 'yes'
    readonly: 'yes'
    guest_ok: 'yes'
sshd_banner_enable: 'false'
sshd_config:
  PermitRootLogin: 'yes'
  UseDNS: 'no'
ntp_config_server : ['0.freebsd.pool.ntp.org' , '1.freebsd.pool.ntp.org', '2.freebsd.pool.ntp.org']
ntp_mode: 'server'
resolv_nameservers:
  - 172.31.3.254
resolv_domain: home
pf_role_enable: True
pf_ftpproxy_enable: True
pf_ip_forward_enable: True
pf_pflogd_enable: True
pf_file_content: "{{ lookup('file','./ressources/new_fw_pf.conf') }}"
pf_tables:
  - name: 'some french IPv4 ranges'
    dest: '/etc/pf_tables/pf.table.fr_ip_range'
    content: "{{ lookup('file','./ressources/pf.table.fr_ip_range') }}"
  - name: 'some trusted IP'
    dest: '/etc/pf_tables/pf.table.trusted_public_ip'
    content: "{{ vault_pf_table_trusted_public_ip }}"

dhcpd_global_max_lease_time: 604800
dhcpd_global_default_lease_time: 432000
dhcpd_authoritative: true
dhcpd_keys:
  - key: "ddns-key"
    algorithm: "hmac-md5"
    secret: "{{ vault_ddns_key_secret }}"
dhcpd_zones:
  - zone: "home.dhcp."
    primary: "127.0.0.1"
    key: "ddns-key"
  - zone: "dhcp.1.31.172.in-addr.arpa."
    primary: "127.0.0.1"
    key: "ddns-key"
dhcpd_options: |
    ddns-updates on;
    ddns-update-style interim;
dhcpd_shared_networks:
  - name: "shared-net"
    subnets: '{{ dhcpd_subnets_local }}' 
    options: |
      option domain-name "home";
      option domain-name-servers 172.31.2.131;
      filename "lpxelinux.0";
dhcpd_subnets_local:
  - subnet: "172.31.2.128"
    netmask: "255.255.255.224"
  - subnet: "172.31.1.0"
    netmask: '255.255.255.0'
    routers: '172.31.1.1'
    options: |
      ddns-domainname "home.dhcp.";
      ddns-rev-domainname "dhcp.1.31.172.in-addr.arpa.";
      ignore client-updates;
    pools:
      - comment: 'first range'
        range: '172.31.1.64 172.31.1.96'
      - comment: 'second range'
        range: '172.31.1.210 172.31.1.240'
  - subnet: "172.31.200.0"
    netmask: "255.255.255.0"
    routers: "172.31.200.4"
    pools:
      - comment: 'range for dmz'
        range: '172.31.200.100 172.31.200.199'
dhcpd_hosts:
  - hostname: 'switch2'
    ethernet: '10:da:43:07:77:2e'
    address: '172.31.1.252'
  - hostname: 'switch3'
    ethernet: '88:15:44:e3:42:2b'
    address: '172.31.1.253'
  - hostname: 'pchc'
    ethernet: '1c:6f:65:44:d2:38'
    address: '172.31.1.201'
  - hostname: 'pc-brice'
    ethernet: 'e0:cb:4e:25:16:a6'
    address: '172.31.1.202'
  - hostname: 'switch1'
    ethernet: '08:cc:68:47:7d:25'
    address: '172.31.1.1'
  - hostname: 'xbox'
    ethernet: '00:50:f2:8a:35:2e'
    address: '172.31.1.203'
  - hostname: 'nuc'
    address: '172.31.1.205'
    ethernet:
      - '00:21:5d:da:9b:88'
      - 'c8:f7:33:8b:58:F8'
  - hostname: 'm00180ad4fac0'
    address: '172.31.1.2'
    ethernet: '00:18:0a:d4:fa:c0'
  - hostname: 'ipmi-bignas'
    address: '172.31.1.4'
    ethernet: 'bc:5f:f4:fe:54:37'
  - hostname: "webcam1"
    ethernet: 'e0:b9:4d:ed:9b:44'
    address: '172.31.200.11'
  - hostname: "webcam2"
    ethernet: 'e0:b9:4d:88:03:9f'
    address: '172.31.200.12'
  - hostname: "rz800"
    ethernet: '00:09:b0:db:42:9e'
    address: '172.31.1.14'

zone_home:
  ns:
    - { rdata: "fw3.home." }
#  mx:
#    - { priority: 10,  rdata: "fw3.home." }
  records:
    - { name: "_vlmcs._tcp" , type: SRV , rdata: "10 0 61688 kms-dmz" }
    - { name: "switch1" , type: A , rdata: "172.31.1.1" }
    - { name: "m00180ad4fac0" , type: A , rdata: "172.31.1.2" }
    - { name: "fwasa1" , type: A , rdata: "172.31.1.3" }
    - { name: "ipmi-bignas" , type: A , rdata: "172.31.1.4" }
    - { name: "asav1" , type: A , rdata: "172.31.1.5" }
    - { name: "esxi1" , type: A , rdata: "172.31.1.6" }
    - { name: "asav2" , type: A , rdata: "172.31.1.7" }
    - { name: "esxi2" , type: A , rdata: "172.31.1.8" }
    - { name: "foreman1" , type: A , rdata: "172.31.1.9" }
    - { name: "log1" , type: A , rdata: "172.31.1.10" }
    - { name: "ansible1" , type: A , rdata: "172.31.1.11" }
    - { name: "esxi2-gns3" , type: A , rdata: "172.31.1.12" }
    - { name: "ids1" , type: A , rdata: "172.31.1.13" }
    - { name: "rz800" , type: A , rdata: "172.31.1.14" }
    - { name: "mon1" , type: A , rdata: "172.31.1.20" }
    - { name: "jgit1" , type: A , rdata: "172.31.1.32" }
    - { name: "jmysql1" , type: A , rdata: "172.31.1.33" }
    - { name: "jdownloader1" , type: A , rdata: "172.31.1.34" }
    - { name: "jtorrent1" , type: A , rdata: "172.31.1.35" }
    - { name: "jactivemq1" , type: A , rdata: "172.31.1.36" }
    - { name: "jldap1" , type: A , rdata: "172.31.1.37" }
    - { name: "jwebphp1" , type: A , rdata: "172.31.1.38" }
    - { name: "jmadsonic1" , type: A , rdata: "172.31.1.42" }
    - { name: "jletsenc1" , type: A , rdata: "172.31.1.43" }
    - { name: "jwebgw1" , type: A , rdata: "172.31.1.47" }
    - { name: "jwebgw2" , type: A , rdata: "172.31.1.48" }
    - { name: "bignas" , type: A , rdata: "172.31.1.200" }
    - { name: "pchc" , type: A , rdata: "172.31.1.201" }
    - { name: "pc-brice" , type: A , rdata: "172.31.1.202" }
    - { name: "xbox" , type: A , rdata: "172.31.1.203" }
    - { name: "nuc" , type: A , rdata: "172.31.1.205" }
    - { name: "switch2" , type: A , rdata: "172.31.1.252" }
    - { name: "switch3" , type: A , rdata: "172.31.1.253" }
    - { name: "fw-vip" , type: A , rdata: "172.31.2.150" }
    - { name: "fw1" , type: A , rdata: "172.31.2.129" }
    - { name: "fw2" , type: A , rdata: "172.31.2.130" }
    - { name: "fw3" , type: A , rdata: "172.31.2.131" }
    - { name: "webcam1" , type: A , rdata: "172.31.200.11" }
    - { name: "webcam2" , type: A , rdata: "172.31.200.12" }
    - { name: "kms-dmz" , type: A , rdata: "172.31.200.100" }
    - { name: "ap1" , type: CNAME , rdata: "m00180ad4fac0" }
    - { name: "old_aumenucesoir" , type: CNAME , rdata: "jwebphp1" }
    - { name: "pkg" , type: CNAME , rdata: "bignas" }
    - { name: "pkg-centos" , type: CNAME , rdata: "bignas" }
    - { name: "pkg-mtier" , type: CNAME , rdata: "bignas" }
    - { name: "pkg-openbsd" , type: CNAME , rdata: "bignas" }
    - { name: "pkg-puppetlabs" , type: CNAME , rdata: "bignas" }
    - { name: "www-aumenucesoir" , type: CNAME , rdata: "bignas" }    
    - { name: "bignas.nfs" , type: A , rdata: "172.30.1.200" }
    - { name: "esxi1.nfs" , type: A , rdata: "172.30.1.1" }
    - { name: "esxi2.nfs" , type: A , rdata: "172.30.1.2" }
    - { name: "storage1.nfs" , type: A , rdata: "172.30.1.13" }

zone_172_31_2_rev:
  records:
    - { name: "129" , type: PTR , rdata: "fw1.home." }
    - { name: "130" , type: PTR , rdata: "fw2.home." }
    - { name: "131" , type: PTR , rdata: "fw3.home." }
    - { name: "150" , type: PTR , rdata: "fw-vip.home." }

zone_172_31_200_rev:
  records:
    - { name: "100" , type: PTR , rdata: "kmz-dmz.home." }
    - { name: "11" , type: PTR , rdata: "webcam1.home." }
    - { name: "12" , type: PTR , rdata: "webcam1.home." }

zone_172_30_1_rev:
  records:
    - { name: "200" , type: PTR , rdata: "bignas.nfs.home." }
    - { name: "1" , type: PTR , rdata: "esxi1.nfs.home." }
    - { name: "2" , type: PTR , rdata: "esxi2.nfs.home." }
    - { name: "13" , type: PTR , rdata: "storage1.nfs.home." }

zone_172_31_1_static_rev:
  records:
    - { name: "1" , type: PTR , rdata: "switch1.home." }
    - { name: "2" , type: PTR , rdata: "ap1.home." }
    - { name: "3" , type: PTR , rdata: "fwasa1.home." }
    - { name: "4" , type: PTR , rdata: "ipmi-bignas.home." }
    - { name: "5" , type: PTR , rdata: "asav1.home." }
    - { name: "6" , type: PTR , rdata: "esxi1.home." }
    - { name: "7" , type: PTR , rdata: "asav2.home." }
    - { name: "8" , type: PTR , rdata: "esxi2.home." }
    - { name: "9" , type: PTR , rdata: "foreman1.home." }
    - { name: "10" , type: PTR , rdata: "log1.home." }
    - { name: "11" , type: PTR , rdata: "ansible1.home." }
    - { name: "12" , type: PTR , rdata: "esxi2-gns3.home." }
    - { name: "13" , type: PTR , rdata: "ids1.home." }
    - { name: "14" , type: PTR , rdata: "rz800.home." }
    - { name: "20" , type: PTR , rdata: "mon1.home." }
    - { name: "32" , type: PTR , rdata: "jgit1.home." }
    - { name: "33" , type: PTR , rdata: "jmysql1.home." }
    - { name: "34" , type: PTR , rdata: "jdownloader1.home." }
    - { name: "35" , type: PTR , rdata: "jtorrent1.home." }
    - { name: "36" , type: PTR , rdata: "jactivemq1.home." }
    - { name: "37" , type: PTR , rdata: "jldap1.home." }
    - { name: "38" , type: PTR , rdata: "jwebphp1.home." }
    - { name: "42" , type: PTR , rdata: "jmadsonic1.home." }
    - { name: "43" , type: PTR , rdata: "jletsenc1.home." }
    - { name: "47" , type: PTR , rdata: "jwebgw1.home." }
    - { name: "48" , type: PTR , rdata: "jwebgw2.home." }
    - { name: "200" , type: PTR , rdata: "bignas.home." }
    - { name: "201" , type: PTR , rdata: "pchc.home." }
    - { name: "202" , type: PTR , rdata: "pc-brice.home." }
    - { name: "203" , type: PTR , rdata: "xbox.home." }
    - { name: "205" , type: PTR , rdata: "nuc.home." }
    - { name: "252" , type: PTR , rdata: "switch2.home." }
    - { name: "253" , type: PTR , rdata: "switch3.home." }

zone_172_31_1_rev: 
  records:
    - { name: "$GENERATE 1-63 $" ,type: CNAME , rdata: "$.static.1.31.172.in-addr.arpa." }
    - { name: "$GENERATE 64-96 $" ,type: CNAME , rdata: "$.1.31.172.dhcp.1.31.172.in-addr.arpa." }
    - { name: "$GENERATE 97-209 $" ,type: CNAME , rdata: "$.static.1.31.172.in-addr.arpa." }
    - { name: "$GENERATE 210-240 $" ,type: CNAME, rdata: "$.1.31.172.dhcp.1.31.172.in-addr.arpa." }
    - { name: "$GENERATE 241-254 $" ,type: CNAME , rdata: "$.static.1.31.172.in-addr.arpa." }

zone_rzp_static_dhcp: "{{ vault_zone_rzp_static_dhcp }}"
bind_blackhole_malwaredomain_blocklist_url: 'http://mirror2.malwaredomains.com/files/justdomains'
bind_zone_loopback_v6_enable: False
bind_dns_fqdn_name: "{{ ansible_host }}"
bind_hostmaster_name: hostmaster.home
bind_acls: 
  - name: goodclients
    addr_list: ['172.16.0.0/12' ,'127.0.0.1','10.0.0.0/8','192.168.0.0/16']
bind_options_allow_recursion: ['goodclients']
bind_options_allow_query: ['goodclients']
bind_options_additionals:
  - 'response-policy { zone "rzp-static-dhcp"; }'
bind_options_listen_ipv4: [ '127.0.0.1' ,'172.31.2.131']
bind_logging_channels:
  - name: default
    out: syslog daemon
    severity: info
  - name: update_log
    severity: "info"
    file: 
      name: "logs/update.log"
      version: 5
      size: "3M"
    print_time: yes
    print_category: yes
    print_severity: yes
  - name: test_log
    file:
      name: "logs/test.log"
bind_logging_categories:
  - name: default
    channels: [ 'default']
  - name: update
    channels: [ 'update_log' ]
bind_keys:
  - key:  "ddns-key"
    algorithm: 'hmac-md5'
    secret: "{{ vault_ddns_key_secret }}"
  - key:  "foreman-key"
    algorithm: 'hmac-md5'
    secret: "{{ vault_foreman_key_secret }}"
bind_zones:
  - name: 'home.dhcp'
    type: master
    dynamic: true
    managed: false
    parameters:
      - 'allow-update { key "ddns-key"; }'
      - 'also-notify  { 172.31.1.200; }'

  - name: 'vmlab.lan'
    type: forward
    forwarders: ['172.30.0.11','172.30.0.12']

  - name: 'home'
    type: master
    managed: true
    content: "{{ zone_home }}"
    parameters:
      - 'also-notify  { 172.31.1.200; }'

  - name: 'mgmt.home'
    type: stub
    parameters:
      - 'masters { 172.30.0.11; 172.30.0.12; }'

  - name: "1.99.10.in-addr.arpa"
    type: forward
    forwarders: ['172.30.0.11','172.30.0.12']

  - name: "2.99.10.in-addr.arpa"
    type: forward
    forwarders: ['172.30.0.11','172.30.0.12']

  - name: "0.30.172.in-addr.arpa"
    type: forward
    forwarders: ['172.30.0.11','172.30.0.12']

  - name: "1.30.172.in-addr.arpa"
    type: master
    managed: true
    content: "{{ zone_172_30_1_rev }}"
    parameters:
      - 'also-notify  { 172.31.1.200; }'

  - name: "2.31.172.in-addr.arpa"
    type: master
    managed: true
    content: "{{ zone_172_31_2_rev }}"
    parameters:
      - 'also-notify  { 172.31.1.200; }'

  - name: "1.31.172.in-addr.arpa"
    type: master
    managed: true
    content: "{{ zone_172_31_1_rev }}"
    parameters:
      - 'also-notify  { 172.31.1.200; }'

  - name: "200.31.172.in-addr.arpa"
    type: master
    managed: true
    content: "{{ zone_172_31_200_rev }}"
    parameters:
      - 'also-notify  { 172.31.1.200; }'

  - name: "static.1.31.172.in-addr.arpa"
    type: master
    managed: true
    content: "{{ zone_172_31_1_static_rev }}"
    parameters:
      - 'also-notify  { 172.31.1.200; }'

  - name: "dhcp.1.31.172.in-addr.arpa"
    type: master
    managed: false
    dynamic: true
    parameters:
      - 'allow-update { key "ddns-key"; }'
      - 'also-notify  { 172.31.1.200; }'

  - name: "rzp-static-dhcp"
    type: master
    managed: true
    dynamic: false
    content: "{{ zone_rzp_static_dhcp }}"
    parameters:
      - 'allow-query { none; }'
openvpn_instance_warrior:
  openvpn_clients_fetch_datas: True
  openvpn_auth: 'SHA512'
  openvpn_host: '{{ vault_openvpn_host_default }}'
  openvpn_connection_alias: "{{ vault_openvpn_connection_alias_default }}"
  openvpn_dev: tun0
  openvpn_topology: subnet
  openvpn_port: 1193
  openvpn_port_nat: 53193
  openvpn_max_clients: 10
  openvpn_server: '172.31.2.64 255.255.255.192'
  openvpn_clients_certs: [ 'brice' ]
  openvpn_use_certs: yes
  openvpn_check_username_in_cert: yes
  openvpn_use_auth_file: yes
  openvpn_use_auth_file_users:
    - "{{ vault_common_users.brice_apr1_user }}"
  openvpn_server_options:
    - 'push "dhcp-option DNS 172.31.2.131"'
    - 'push "route 172.31.0.0 255.255.0.0"'
    - 'push "route 172.30.0.0 255.255.0.0"'
    - 'push "route 10.99.0.0 255.255.0.0"'
