---
samba_interfaces: 'vmx0'
samba_additional_settings:
  - "map to guest = bad user"
  - "guest account = nobody"
  - "bind interfaces only = yes"
samba_shares:
  - name: tftp
    path: /tftpboot
    public: 'yes'
    readonly: 'yes'
    guest_ok: 'yes'
sshd_banner_enable: 'false'
sshd_config:
  PermitRootLogin: 'yes'
  UseDNS: 'no'
ntp_config_server : ['0.freebsd.pool.ntp.org' , '1.freebsd.pool.ntp.org', '2.freebsd.pool.ntp.org']
ntp_mode: 'server'
resolv_nameservers:
  - 127.0.0.1
resolv_domain: home
pf_role_enable: True
pf_ftpproxy_enable: True
pf_ip_forward_enable: True
pf_file_content: "{{ lookup('file','./ressources/new_fw_pf.conf') }}"
pf_tables:
  - name: 'some french IPv4 ranges'
    dest: '/etc/pf_tables/pf.table.fr_ip_range'
    content: "{{ lookup('file','./ressources/pf.table.fr_ip_range') }}"
  - name: 'some trusted IP'
    dest: '/etc/pf_tables/pf.table.trusted_public_ip'
    content: "{{ vault_pf_table_trusted_public_ip }}"

dhcpd_authoritative: true
dhcpd_keys:
  - key: "ddns-key"
    algorithm: "hmac-md5"
    secret: "{{ vault_ddns_key_secret }}"
dhcpd_zones:
  - zone: "home.dhcp."
    primary: "127.0.0.1"
    key: "ddns-key"
  - zone: "dhcp.1.31.172.in-addr.arpa."
    primary: "127.0.0.1"
    key: "ddns-key"
dhcpd_options: |
    ddns-updates on;
    ddns-update-style interim;
dhcpd_shared_networks:
  - name: "shared-net"
    subnets: '{{ dhcpd_subnets_local }}' 
    options: |
      default-lease-time 600;
      max-lease-time 900;
      option domain-name "home";
      option domain-name-servers 172.31.2.131;
      filename "lpxelinux.0";
dhcpd_subnets_local:
  - subnet: "172.31.2.128"
    netmask: "255.255.255.224"
  - subnet: "172.31.1.0"
    netmask: '255.255.255.0'
    router: '172.31.1.254'
    options: |
      ddns-domainname "home.dhcp.";
      ddns-rev-domainname "dhcp.1.31.172.in-addr.arpa.";
      ignore client-updates;
    pools:
      - comment: 'first range'
        range: '172.31.1.64 172.31.1.96'
      - comment: 'second range'
        range: '172.31.1.210 172.31.1.240'
  - subnet: "172.31.200.0"
    netmask: "255.255.255.0"
    router: "172.31.200.4"
    pools:
      - comment: 'range for dmz'
        range: '172.31.200.100 172.31.200.199'
dhcpd_hosts:
  - hostname: 'switch3'
    ethernet: '10:da:43:07:77:2e'
    address: '172.31.1.252'
  - hostname: 'pchc'
    ethernet: '1c:6f:65:44:d2:38'
    address: '172.31.1.201'
  - hostname: 'pc-brice'
    ethernet: 'e0:cb:4e:25:16:a6'
    address: '172.31.1.202'
  - hostname: 'switch1'
    ethernet: '08:cc:68:47:7d:25'
    address: '172.31.1.1'
  - hostname: 'xbox'
    ethernet: '00:50:f2:8a:35:2e'
    address: '172.31.1.203'
  - hostname: 'nuc'
    address: '172.31.1.205'
    ethernet:
      - '00:21:5d:da:9b:88'
      - 'c8:f7:33:8b:58:F8'
  - hostname: 'ap01'
    address: '172.31.1.2'
    ethernet: '00:18:0a:d4:fa:c0'
  - hostname: 'ipmi-bignas'
    address: '172.31.1.4'
    ethernet: 'bc:5f:f4:fe:54:37'
  - hostname: "webcam1"
    ethernet: 'e0:b9:4d:ed:9b:44'
    address: '172.31.200.11'
  - hostname: "webcam2"
    ethernet: 'e0:b9:4d:88:03:9f'
    address: '172.31.200.12'

zone_home:
  ns:
    - { rdata: "fw-gw.home." }
#  mx:
#    - { priority: 10,  rdata: "fw-gw.home." }
  records:
    - { name: "switch1" , type: A , rdata: "172.31.1.1" }
    - { name: "m00180ad4fac0" , type: A , rdata: "172.31.1.2" }
    - { name: "fwasa1" , type: A , rdata: "172.31.1.3" }
    - { name: "ipmi-bignas" , type: A , rdata: "172.31.1.4" }
    - { name: "asav1" , type: A , rdata: "172.31.1.5" }
    - { name: "esxi1" , type: A , rdata: "172.31.1.6" }
    - { name: "asav2" , type: A , rdata: "172.31.1.7" }
    - { name: "esxi2" , type: A , rdata: "172.31.1.8" }
    - { name: "foreman1" , type: A , rdata: "172.31.1.9" }
    - { name: "log1" , type: A , rdata: "172.31.1.10" }
    - { name: "ansible1" , type: A , rdata: "172.31.1.11" }
    - { name: "esxi2-gns3" , type: A , rdata: "172.31.1.12" }
    - { name: "ids1" , type: A , rdata: "172.31.1.13" }
    - { name: "mon1" , type: A , rdata: "172.31.1.20" }
    - { name: "jgit1" , type: A , rdata: "172.31.1.32" }
    - { name: "jmysql1" , type: A , rdata: "172.31.1.33" }
    - { name: "jdownloader1" , type: A , rdata: "172.31.1.34" }
    - { name: "jtorrent1" , type: A , rdata: "172.31.1.35" }
    - { name: "jactivemq1" , type: A , rdata: "172.31.1.36" }
    - { name: "jldap1" , type: A , rdata: "172.31.1.37" }
    - { name: "jwebphp1" , type: A , rdata: "172.31.1.38" }
    - { name: "jmadsonic1" , type: A , rdata: "172.31.1.42" }
    - { name: "jletsenc1" , type: A , rdata: "172.31.1.43" }
    - { name: "jwebgw1" , type: A , rdata: "172.31.1.47" }
    - { name: "jwebgw2" , type: A , rdata: "172.31.1.48" }
    - { name: "bignas" , type: A , rdata: "172.31.1.200" }
    - { name: "pchc" , type: A , rdata: "172.31.1.201" }
    - { name: "pc-brice" , type: A , rdata: "172.31.1.202" }
    - { name: "xbox" , type: A , rdata: "172.31.1.203" }
    - { name: "nuc" , type: A , rdata: "172.31.1.205" }
    - { name: "switch3" , type: A , rdata: "172.31.1.252" }
    - { name: "switch2" , type: A , rdata: "172.31.1.253" }
    - { name: "fw-vip" , type: A , rdata: "172.31.2.150" }
    - { name: "fw1" , type: A , rdata: "172.31.2.129" }
    - { name: "fw2" , type: A , rdata: "172.31.2.130" }
    - { name: "fw-gw" , type: A , rdata: "172.31.2.131" }
    - { name: "webcam1" , type: A , rdata: "172.31.200.11" }
    - { name: "webcam2" , type: A , rdata: "172.31.200.12" }
    - { name: "kms-dmz" , type: A , rdata: "172.31.200.100" }
    - { name: "_vlmcs._tcp" , type: SRV , rdata: "10 0 61688 kmz-dmz" }
    - { name: "ap1" , type: CNAME , rdata: "m00180ad4fac0" }
    - { name: "old_aumenucesoir" , type: CNAME , rdata: "jwebphp1" }
    - { name: "pkg-centos" , type: CNAME , rdata: "bignas" }
    - { name: "pkg-mtier" , type: CNAME , rdata: "bignas" }
    - { name: "pkg-openbsd" , type: CNAME , rdata: "bignas" }
    - { name: "pkg-puppetlabs" , type: CNAME , rdata: "bignas" }
    - { name: "www-aumenucesoir" , type: CNAME , rdata: "bignas" }    
zone_172_31_2_rev:
  records:
    - { name: "131", type: "PTR" , rdata: "fw-gw.home." }
zone_172_30_1_rev:
  records: []
zone_172_31_1_static_rev:
  records:
    - { name: "48", type: "PTR" , rdata: "jwebgw2.home." }
zone_172_31_1_rev: 
  records:
    - { name: "$GENERATE 1-63 $" ,type: CNAME , rdata: "$.static.1.31.172.in-addr.arpa." }
    - { name: "$GENERATE 64-96 $" ,type: CNAME , rdata: "$.1.31.172.dhcp.1.31.172.in-addr.arpa." }
    - { name: "$GENERATE 97-209 $" ,type: CNAME , rdata: "$.static.1.31.172.in-addr.arpa." }
    - { name: "$GENERATE 210-240 $" ,type: CNAME, rdata: "$.1.31.172.dhcp.1.31.172.in-addr.arpa." }
    - { name: "$GENERATE 241-254 $" ,type: CNAME , rdata: "$.static.1.31.172.in-addr.arpa." }
zone_rzp_static_dhcp: "{{ vault_zone_rzp_static_dhcp }}"
bind_zone_loopback_v6_enable: False
bind_dns_fqdn_name: "{{ ansible_host }}"
bind_hostmaster_name: hostmaster.home
bind_acls: 
  - name: goodclients
    addr_list: ['172.16.0.0/16' ,'127.0.0.1','10.0.0.0/8','192.168.0.0/16']
bind_options_allow_recursion: ['goodclients']
bind_options_allow_query: ['goodclients']
bind_options_additionals:
  - 'response-policy { zone "rzp-static-dhcp"; }'
bind_logging_channels:
  - name: default
    out: syslog daemon
    severity: info
  - name: update_log
    severity: "info"
    file: 
      name: "logs/update.log"
      version: 5
      size: "3M"
    print_time: yes
    print_category: yes
    print_severity: yes
  - name: test_log
    file:
      name: "logs/test.log"
bind_logging_categories:
  - name: default
    channels: [ 'default']
  - name: update
    channels: [ 'update_log' ]
bind_keys:
  - key:  "ddns-key"
    algorithm: 'hmac-md5'
    secret: "{{ vault_ddns_key_secret }}"
  - key:  "foreman-key"
    algorithm: 'hmac-md5'
    secret: "{{ vault_foreman_key_secret }}"
bind_zones:
  - name: 'home.dhcp'
    type: master
    dynamic: true
    managed: false
    parameters:
      - 'allow-update { key "ddns-key"; }'
  - name: 'vmlab.lan'
    type: forward
    forwarders: ['172.30.0.11','172.30.0.12']
  - name: 'home'
    type: master
    managed: true
    content: "{{ zone_home }}"
  - name: "1.99.10.in-addr.arpa"
    type: forward
    forwarders: ['172.30.0.11','172.30.0.12']
  - name: "2.99.10.in-addr.arpa"
    type: forward
    forwarders: ['172.30.0.11','172.30.0.12']
  - name: "0.30.172.in-addr.arpa"
    type: forward
    forwarders: ['172.30.0.11','172.30.0.12']
  - name: "1.30.172.in-addr.arpa"
    type: master
    managed: true
    content: "{{ zone_172_30_1_rev }}"
  - name: "2.31.172.in-addr.arpa"
    type: master
    managed: true
    content: "{{ zone_172_31_2_rev }}"
  - name: "1.31.172.in-addr.arpa"
    type: master
    managed: true
    content: "{{ zone_172_31_1_rev }}"
  - name: "static.1.31.172.in-addr.arpa"
    type: master
    managed: true
    content: "{{ zone_172_31_1_static_rev }}"
  - name: "dhcp.1.31.172.in-addr.arpa"
    type: master
    managed: false
    dynamic: true
    parameters:
      - 'allow-update { key "ddns-key"; }'
  - name: "rzp-static-dhcp"
    type: master
    managed: true
    dynamic: false
    content: "{{ zone_rzp_static_dhcp }}"
    parameters:
      - 'allow-query { none; }'
openvpn_instance_default:
  openvpn_clients_fetch_datas: True
  openvpn_auth: 'SHA512'
  openvpn_host: '{{ vault_openvpn_host_default }}'
  openvpn_connection_alias: "{{ vault_openvpn_connection_alias_default }}"
  openvpn_dev: tun0
  openvpn_topology: subnet
  openvpn_port: 1193
  openvpn_port_nat: 51193
  openvpn_max_clients: 10
  openvpn_server: '172.31.2.64 255.255.255.192'
  openvpn_clients_certs: [ 'brice' ]
  openvpn_use_certs: yes
  openvpn_check_username_in_cert: yes
  openvpn_use_auth_file: yes
  openvpn_use_auth_file_users:
    - "{{ vault_common_users.brice_apr1_user }}"
  openvpn_server_options:
    - 'push "dhcp-option DNS 172.31.2.131"'
    - 'push "route 172.31.0.0 255.255.0.0"'
    - 'push "route 172.30.0.0 255.255.0.0"'
    - 'push "route 10.99.0.0 255.255.0.0"'


